"""
Phase 2 conditional pipeline execution mapping.

Defines the list of canonical Phase 1 event types and the corresponding analyzer
scripts and arguments required to process them in Phase 2 candidate discovery.
"""
import sys
from typing import List, Tuple

PHASE2_EVENT_CHAIN: List[Tuple[str, str, List[str]]] = [
    ('VOL_SHOCK', 'analyze_vol_shock_relaxation.py', ['--timeframe', '5m']),
    ('LIQUIDITY_VACUUM', 'analyze_liquidity_vacuum.py', ['--timeframe', '5m']),
    ('FORCED_FLOW_EXHAUSTION', 'analyze_directional_exhaustion_after_forced_flow.py', []),
    ('CROSS_VENUE_DESYNC', 'analyze_cross_venue_desync.py', []),
    ('FUNDING_EXTREME_ONSET', 'analyze_funding_episode_events.py', []),
    ('FUNDING_PERSISTENCE_TRIGGER', 'analyze_funding_episode_events.py', []),
    ('FUNDING_NORMALIZATION_TRIGGER', 'analyze_funding_episode_events.py', []),
    ('OI_SPIKE_POSITIVE', 'analyze_oi_shock_events.py', []),
    ('OI_SPIKE_NEGATIVE', 'analyze_oi_shock_events.py', []),
    ('OI_FLUSH', 'analyze_oi_shock_events.py', []),
    ('LIQUIDATION_CASCADE', 'analyze_liquidation_cascade.py', []),
    ('DEPTH_COLLAPSE', 'analyze_liquidity_dislocation_events.py', ['--event_type', 'DEPTH_COLLAPSE', '--timeframe', '5m']),
    ('SPREAD_BLOWOUT', 'analyze_liquidity_dislocation_events.py', ['--event_type', 'SPREAD_BLOWOUT', '--timeframe', '5m']),
    ('ORDERFLOW_IMBALANCE_SHOCK', 'analyze_liquidity_dislocation_events.py', ['--event_type', 'ORDERFLOW_IMBALANCE_SHOCK', '--timeframe', '5m']),
    ('SWEEP_STOPRUN', 'analyze_liquidity_dislocation_events.py', ['--event_type', 'SWEEP_STOPRUN', '--timeframe', '5m']),
    ('ABSORPTION_EVENT', 'analyze_liquidity_dislocation_events.py', ['--event_type', 'ABSORPTION_EVENT', '--timeframe', '5m']),
    ('LIQUIDITY_GAP_PRINT', 'analyze_liquidity_dislocation_events.py', ['--event_type', 'LIQUIDITY_GAP_PRINT', '--timeframe', '5m']),
    ('VOL_SPIKE', 'analyze_volatility_transition_events.py', ['--event_type', 'VOL_SPIKE', '--timeframe', '5m']),
    ('VOL_RELAXATION_START', 'analyze_volatility_transition_events.py', ['--event_type', 'VOL_RELAXATION_START', '--timeframe', '5m']),
    ('VOL_CLUSTER_SHIFT', 'analyze_volatility_transition_events.py', ['--event_type', 'VOL_CLUSTER_SHIFT', '--timeframe', '5m']),
    ('RANGE_COMPRESSION_END', 'analyze_volatility_transition_events.py', ['--event_type', 'RANGE_COMPRESSION_END', '--timeframe', '5m']),
    ('BREAKOUT_TRIGGER', 'analyze_volatility_transition_events.py', ['--event_type', 'BREAKOUT_TRIGGER', '--timeframe', '5m']),
    ('FUNDING_FLIP', 'analyze_positioning_extremes_events.py', ['--event_type', 'FUNDING_FLIP', '--timeframe', '5m']),
    ('DELEVERAGING_WAVE', 'analyze_positioning_extremes_events.py', ['--event_type', 'DELEVERAGING_WAVE', '--timeframe', '5m']),
    ('TREND_EXHAUSTION_TRIGGER', 'analyze_forced_flow_and_exhaustion_events.py', ['--event_type', 'TREND_EXHAUSTION_TRIGGER', '--timeframe', '5m']),
    ('MOMENTUM_DIVERGENCE_TRIGGER', 'analyze_forced_flow_and_exhaustion_events.py', ['--event_type', 'MOMENTUM_DIVERGENCE_TRIGGER', '--timeframe', '5m']),
    ('CLIMAX_VOLUME_BAR', 'analyze_forced_flow_and_exhaustion_events.py', ['--event_type', 'CLIMAX_VOLUME_BAR', '--timeframe', '5m']),
    ('FAILED_CONTINUATION', 'analyze_forced_flow_and_exhaustion_events.py', ['--event_type', 'FAILED_CONTINUATION', '--timeframe', '5m']),
    ('RANGE_BREAKOUT', 'analyze_trend_structure_events.py', ['--event_type', 'RANGE_BREAKOUT', '--timeframe', '5m']),
    ('FALSE_BREAKOUT', 'analyze_trend_structure_events.py', ['--event_type', 'FALSE_BREAKOUT', '--timeframe', '5m']),
    ('TREND_ACCELERATION', 'analyze_trend_structure_events.py', ['--event_type', 'TREND_ACCELERATION', '--timeframe', '5m']),
    ('TREND_DECELERATION', 'analyze_trend_structure_events.py', ['--event_type', 'TREND_DECELERATION', '--timeframe', '5m']),
    ('PULLBACK_PIVOT', 'analyze_trend_structure_events.py', ['--event_type', 'PULLBACK_PIVOT', '--timeframe', '5m']),
    ('SUPPORT_RESISTANCE_BREAK', 'analyze_trend_structure_events.py', ['--event_type', 'SUPPORT_RESISTANCE_BREAK', '--timeframe', '5m']),
    ('ZSCORE_STRETCH', 'analyze_statistical_dislocation_events.py', ['--event_type', 'ZSCORE_STRETCH', '--timeframe', '5m']),
    ('BAND_BREAK', 'analyze_statistical_dislocation_events.py', ['--event_type', 'BAND_BREAK', '--timeframe', '5m']),
    ('OVERSHOOT_AFTER_SHOCK', 'analyze_statistical_dislocation_events.py', ['--event_type', 'OVERSHOOT_AFTER_SHOCK', '--timeframe', '5m']),
    ('GAP_OVERSHOOT', 'analyze_statistical_dislocation_events.py', ['--event_type', 'GAP_OVERSHOOT', '--timeframe', '5m']),
    ('VOL_REGIME_SHIFT_EVENT', 'analyze_regime_transition_events.py', ['--event_type', 'VOL_REGIME_SHIFT_EVENT', '--timeframe', '5m']),
    ('TREND_TO_CHOP_SHIFT', 'analyze_regime_transition_events.py', ['--event_type', 'TREND_TO_CHOP_SHIFT', '--timeframe', '5m']),
    ('CHOP_TO_TREND_SHIFT', 'analyze_regime_transition_events.py', ['--event_type', 'CHOP_TO_TREND_SHIFT', '--timeframe', '5m']),
    ('CORRELATION_BREAKDOWN_EVENT', 'analyze_regime_transition_events.py', ['--event_type', 'CORRELATION_BREAKDOWN_EVENT', '--timeframe', '5m']),
    ('BETA_SPIKE_EVENT', 'analyze_regime_transition_events.py', ['--event_type', 'BETA_SPIKE_EVENT', '--timeframe', '5m']),
    ('INDEX_COMPONENT_DIVERGENCE', 'analyze_information_desync_events.py', ['--event_type', 'INDEX_COMPONENT_DIVERGENCE', '--timeframe', '5m']),
    ('SPOT_PERP_BASIS_SHOCK', 'analyze_information_desync_events.py', ['--event_type', 'SPOT_PERP_BASIS_SHOCK', '--timeframe', '5m']),
    ('LEAD_LAG_BREAK', 'analyze_information_desync_events.py', ['--event_type', 'LEAD_LAG_BREAK', '--timeframe', '5m']),
    ('SESSION_OPEN_EVENT', 'analyze_temporal_structure_events.py', ['--event_type', 'SESSION_OPEN_EVENT', '--timeframe', '5m']),
    ('SESSION_CLOSE_EVENT', 'analyze_temporal_structure_events.py', ['--event_type', 'SESSION_CLOSE_EVENT', '--timeframe', '5m']),
    ('FUNDING_TIMESTAMP_EVENT', 'analyze_temporal_structure_events.py', ['--event_type', 'FUNDING_TIMESTAMP_EVENT', '--timeframe', '5m']),
    ('SCHEDULED_NEWS_WINDOW_EVENT', 'analyze_temporal_structure_events.py', ['--event_type', 'SCHEDULED_NEWS_WINDOW_EVENT', '--timeframe', '5m']),
    ('SPREAD_REGIME_WIDENING_EVENT', 'analyze_execution_friction_events.py', ['--event_type', 'SPREAD_REGIME_WIDENING_EVENT', '--timeframe', '5m']),
    ('SLIPPAGE_SPIKE_EVENT', 'analyze_execution_friction_events.py', ['--event_type', 'SLIPPAGE_SPIKE_EVENT', '--timeframe', '5m']),
    ('FEE_REGIME_CHANGE_EVENT', 'analyze_execution_friction_events.py', ['--event_type', 'FEE_REGIME_CHANGE_EVENT', '--timeframe', '5m']),
    ('COPULA_PAIRS_TRADING', 'analyze_copula_pairs.py', ['--pairs', 'BTCUSDT:ETHUSDT']),
    ('FND_DISLOC', 'analyze_funding_dislocation.py', ['--timeframe', '5m']),
    ('BASIS_DISLOC', 'analyze_basis_dislocation.py', ['--timeframe', '5m']),
]
